services:

  nginx:
    image: nginx:stable-alpine
    container_name: prod_nginx
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - '/etc/letsencrypt:/etc/letsencrypt'
      - '/var/docker/nginx/logs:/var/log/nginx'
    ports:
      - 443:443
      - 80:80
    networks:
      nginx_net:

networks:
  nginx_net:
    driver: bridge
    name: nginx_net
#    ipam:
#      driver: default
#      config:
#          - subnet: 10.11.13.0/24
